### ISSUE TITLE
wiki.Wiki fails due to AttributeError in api.py

### ISSUE THREAD

**Issue by lcoustillac** [elsiehupp/wikitools3#8]
Hi, I am migrating a python 2.7 script to python3; it uses wikitools therefore I am trying to use wikitools3 instead.

Alas my script fails. If I simplify my script extremely it looks like this :
```python
#!/usr/bin/env python

from wikitools3 import wiki

api_url = "http://my.wikisite.org/w/api.php"
site = wiki.Wiki(api_url)
```
Now I run my script (that I named test_wikitools.py) and it fails like this :
```
Traceback (most recent call last):
  File "./test_wikitools.py", line 6, in <module>
    site = wiki.Wiki(api_url)
  File "/usr/local/lib/python3.8/site-packages/wikitools3/wiki.py", line 112, in __init__
    self.setSiteinfo()
  File "/usr/local/lib/python3.8/site-packages/wikitools3/wiki.py", line 130, in setSiteinfo
    req = api.APIRequest(self, params)
  File "/usr/local/lib/python3.8/site-packages/wikitools3/api.py", line 86, in __init__
    self.encodeddata = urlencode(self.data, 1)
  File "/usr/local/lib/python3.8/site-packages/wikitools3/api.py", line 427, in urlencode
    elif v.type(str):
AttributeError: 'int' object has no attribute 'type'
```
I tried using python 3.8, 3.10 and 3.12 and obtained the same result. I installed wikitools3  using pip, and a 3.0.1 version came. I am doing all this on ubuntu 20.04 or 22.04 depending on attempts.

Am I doing something wrong? Any input would be welcome.

**Comment by lcoustillac** [comment]
As I did some debugging, it appears that that `query` hash at line 417 happens to have a key `maxlag` with value `120` which is of type int.

I tried inserting these two lines beween line 426 and 427 in api.py so that python doesn't try running the test at line 427:
```python
            if isinstance(v, str):
                v = quote_plus(v)
                l.append(k + "=" + v)  # <- this is line 426
            elif isinstance(v, int):
                l.append(k + "=" + str(v))
            elif v.type(str):  # <- this was line 427
```
Alas now my script fails for some other reason:
```
Traceback (most recent call last):
  File "./test_wikitools.py", line 7, in <module>
    site = wiki.Wiki(api_url, preauth=False)
  File "/usr/local/lib/python3.8/site-packages/wikitools3/wiki.py", line 112, in __init__
    self.setSiteinfo()
  File "/usr/local/lib/python3.8/site-packages/wikitools3/wiki.py", line 130, in setSiteinfo
    req = api.APIRequest(self, params)
  File "/usr/local/lib/python3.8/site-packages/wikitools3/api.py", line 101, in __init__
    self.opener = urllib.build_opener(
AttributeError: module 'urllib' has no attribute 'build_opener'
```

**Comment by yzqzss** [comment]
This issue has been fixed in #6

**Comment by lcoustillac** [comment]
Great, thanks for your feedback. I understand this commit is not present on release 3.0.1; do you happen to know when a new release will be available?

(Right now I will try using the develop branch).

**Comment by lcoustillac** [comment]
(Making new issues as I experience new problems).
